Description: Creating EC2 resources for lab 6.1.1
Resources:
  DebianLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AMI
        InstanceType: t2.medium
  DebianASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref DebianLaunchTemplate
        Version: 1
      MaxSize: '2'
      MinSize: '1'
      DesiredCapacity: '2'
      AvailabilityZones: 
        - us-west-1a
        - us-west-1b
        - us-west-1c
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: True


Parameters:
  AMI:
    Type: String
  Keyname:
    Type: String 