Description: Creating EC2 resources for lab 5.1.2
Resources:
  DefaultLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        InstanceType: t2.micro
        KeyName: greysongundrumkeypair512
      LaunchTemplateName: greysongundrumLT512
      VersionDescription: 1

  LinuxInstance:
    Type: AWS::EC2::Instance
    Properties: 
      LaunchTemplate:
        LaunchTemplateId: !Ref DefaultLaunchTemplate
        Version: 1
      ImageId: ami-02ea247e531eb3ce6
      SubnetId: !Ref DefaultSubnet
      AvailabilityZone: us-west-1a
      SecurityGroupIds: 
         - !Ref PingSG

  DefaultVpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.55.0.0/24

  DefaultSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.55.0.0/24
      VpcId: !Ref DefaultVpc
      AvailabilityZone: us-west-1a

  LinuxInstanceEIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref LinuxInstance
    DependsOn: DefaultInternetGatewayAttach

  DefaultInternetGateway:
    Type: AWS::EC2::InternetGateway

  DefaultInternetGatewayAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref DefaultInternetGateway
      VpcId: !Ref DefaultVpc
      
  InternetGatewayRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref DefaultVpc
  
  DefaultRouteToInternetGatway:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref DefaultInternetGateway
      RouteTableId: !Ref InternetGatewayRouteTable
  
  DefaultRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref InternetGatewayRouteTable
      SubnetId: !Ref DefaultSubnet

  DefaultInternetGatewayEIP:
    Type: AWS::EC2::EIP

  PingSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow ping into instance.
      GroupName: PingSG
      SecurityGroupIngress: 
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref DefaultVpc

Outputs:
  LinuxInstanceEIPOutput:
    Description: Public IPv4 address for the EIP that is attached to the linux instance
    Value: !Ref LinuxInstanceEIP
    Export:
      Name: NameyMcNamerton