Description: Creating EC2 Resources for lab 4.1.4
Resources:
  EC2I1: 
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !ImportValue greysongundrum412-SubnetID
      ImageId: !Ref ImageId
      KeyName: !Ref KeyPair
      InstanceType: !Ref Size
      SecurityGroupIds: [!Ref PingSG]
      Tags:
      - Key: user
        Value: greyson.gundrum.labs
      - Key: stelligent-u-lesson
        Value: 4
      - Key: stelligent-u-lab
        Value: 411
  PingSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows ping to an EC2 Instance
      VpcId: !ImportValue greysongundrum412-VPCID
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: user
        Value: greyson.gundrum.labs
      - Key: stelligent-u-lesson
        Value: 4
      - Key: stelligent-u-lab
        Value: 411
  EIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref EC2I1
Parameters:
  ImageId:
    Type: String
    Default: ami-09208e69ff3feb1db
    Description: Most recent Linxu Amazon AMI
  Size:
    Type: String
    Default: t2.micro
    Description: Smallest type of instance for cheapest price
  KeyPair:
    Type: String
    Default: greysongundrumkeypair413
    Description: Key pair for SSH access
Outputs:
  InstanceIP:
    Description: The private IP address of the instance
    Value: !GetAtt EC2I1.PrivateIp
    Export: 
      Name: !Sub "${AWS::StackName}-SubnetID"
  InstanceID:
    Description: The ID of the Instance for reference when using other resources
    Value: !Ref EC2I1
    Export:
      Name: !Sub "${AWS::StackName}-InstanceID"
  PublicEIP:
    Description: IPv4 address of Elastic IP
    Value: !Ref EIP
    Export:
      Name: !Sub "${AWS::StackName}-EIP"
