AWSTemplateFormatVersion: '2010-09-09'
Description: Troubleshooting my lab
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      Tags:
      - Key: user
        Value: greyson.gundrum.labs
      - Key: stelligent-u-lesson
        Value: 4
      - Key: stelligent-u-lab
        Value: 499
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref VPC
      Tags:
      - Key: user
        Value: greyson.gundrum.labs
      - Key: stelligent-u-lesson
        Value: 4
      - Key: stelligent-u-lab
        Value: 411
  EC2I1: 
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref PublicSubnet
      ImageId: !Ref ImageId
      KeyName: !Ref KeyPair
      InstanceType: !Ref Size
      SecurityGroupIds: [!Ref PingSG]
      Tags:
      - Key: user
        Value: greyson.gundrum.labs
      - Key: stelligent-u-lesson
        Value: 4
      - Key: stelligent-u-lab
        Value: 411
  PingSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows ping and SSH to EC2
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: 8
          ToPort: 0
          CidrIp: 0.0.0.0/0
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: user
        Value: greyson.gundrum.labs
      - Key: stelligent-u-lesson
        Value: 4
      - Key: stelligent-u-lab
        Value: 411
  EIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref EC2I1
  VPCIG:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: user
        Value: greyson.gundrum.labs
      - Key: stelligent-u-lesson
        Value: 4
      - Key: stelligent-u-lab
        Value: 411
  IGAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref VPC
      InternetGatewayId: !Ref VPCIG
  RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: user
        Value: greyson.gundrum.labs
      - Key: stelligent-u-lesson
        Value: 4
      - Key: stelligent-u-lab
        Value: 411
  Route2IG:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RT
      GatewayId: !Ref VPCIG
      DestinationCidrBlock: 0.0.0.0/0
  RT2SAttach:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RT
  NACL1:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: user
        Value: greyson.gundrum.labs
      - Key: stelligent-u-lesson
        Value: 4
      - Key: stelligent-u-lab
        Value: 418
  InboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: NACL1
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: 173.19.144.189/32
      PortRange:
        From: 22
        To: 22
  OutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: NACL1
       RuleNumber: 101
       Protocol: -1
       Egress: true
       RuleAction: allow
       CidrBlock: 0.0.0.0/0
  NACL1ASC:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: !Ref NACL1
      SubnetId: !Ref PublicSubnet

Parameters:
  VPCCidrBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: Network address and CIDR in 0.0.0.0/0 format. 
  ImageId:
    Type: String
    Default: ami-09208e69ff3feb1db
    Description: Most recent Linxu Amazon AMI
  Size:
    Type: String
    Default: t2.micro
    Description: Smallest type of instance for cheapest price
  KeyPair:
    Type: String
    Default: greysongundrumkeypair413
    Description: Key pair for SSH access
