Resources:
  greysongundrumstelligentucfbucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      LifecycleConfiguration:
        Rules:
          - Id: mv2IA
            Prefix: IA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
            NoncurrentVersionExpirationInDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: mv2glacier
            Prefix: GLACIER
            Status: Enabled
            Transitions: 
              - TransitionInDays: 0
                StorageClass: GLACIER
          - Id: expire1day
            Prefix: 'trash/'
            Status: Enabled
            ExpirationInDays: 1
            TagFilters: 
              -  Key: Name
                 Value: "GreysonBucket"
      Tags:
        - Key: "Name"
          Value: "GreysonBucket"
      VersioningConfiguration:
        Status: Enabled
      
