Description: Creating EC2 resources for lab 8.2.1
Resources:
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: aws-cloudtrail-logs-324320755747-cca64b38
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: 
              - cloudtrail.amazonaws.com
          Action: s3:GetBucketAcl
          Resource: arn:aws:s3:::aws-cloudtrail-logs-324320755747-cca64b38
        - Effect: Allow
          Principal:
            Service: 
              - cloudtrail.amazonaws.com
          Action: s3:PutObject
          Resource: arn:aws:s3:::aws-cloudtrail-logs-324320755747-cca64b38/AWSLogs/324320755747/*
          Condition:
            StringEquals:
              s3:x-amz-acl: bucket-owner-full-control
  
  LabTrailTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: aws-cloudtrail-logs-324320755747-cca64b38
      IsLogging: true
      CloudWatchLogsLogGroupArn: !GetAtt LabLogLog.Arn
      CloudWatchLogsRoleArn: !GetAtt MyCloudWatchRole.Arn
              

  LabLogLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 5
      LogGroupName: GreysonGundrumLogGroup821

  MyCloudWatchRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "cloud-watch-logs"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"