Description: Creating IAM resource for lab 3.1.2
Resources:
  IAMReadonly:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  iamreadonlymanagedpolicy:            
    Type: AWS::IAM::ManagedPolicy
    DependsOn: IAMReadonly
    Properties:
      ManagedPolicyName: ManagedPolicyforIAMread
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'IAM:Describe*'
            Resource: '*'
      Roles: [!Ref IAMReadonly]