Description: Creating IAM resource for lab 3.1.1
Resources:
  IAMReadonly:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:z
              - 'sts:AssumeRole'
  AnotherIAMReadonly:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  iamreadonlymanagedpolicy:      
    Description: Used in two roles IAMReadonly and AnotherIAMReadonly        
    Type: AWS::IAM::ManagedPolicy
    DependsOn: IAMReadonly
    Properties:
      ManagedPolicyName: ManagedPolicyforIAMread
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'IAM:Describe*'
            Resource: '*'
      Roles: [!Ref IAMReadonly, !Ref AnotherIAMReadonly]