AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WebServersLC:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: !Ref AMI
      InstanceType: 't2.micro'
      KeyName: !Ref Keyname
      SecurityGroups:
        - !ImportValue greysongundrumnetworkstack-PingSG
      UserData: 
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            sudo amazon-linux-extras install -y nginx1
            sudo service nginx start
            sudo echo "<p>Automation for the People</p>" > /usr/share/nginx/html/index.html

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: instance
      Port: 80
      Protocol: HTTP
      HealthCheckPath: "/BADindex.html"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher: 
          HttpCode: "200"
      HealthCheckEnabled: true
      VpcId: !ImportValue greysongundrumnetworkstack-VPCID

  WebServerAsg:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      DesiredCapacity: 2
      HealthCheckType: 'ELB'
      HealthCheckGracePeriod: 30 
      LaunchConfigurationName: !Ref WebServersLC
      MaxSize: 2
      MinSize: 1
      TargetGroupARNs:
        - !Ref MyTargetGroup
      VPCZoneIdentifier:
        - !ImportValue greysongundrumnetworkstack-PublicSubnet1
        - !ImportValue greysongundrumnetworkstack-PublicSubnet2
        - !ImportValue greysongundrumnetworkstack-PublicSubnet3

  greysongundrumLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - !ImportValue greysongundrumnetworkstack-PublicSubnet1
        - !ImportValue greysongundrumnetworkstack-PublicSubnet2
        - !ImportValue greysongundrumnetworkstack-PublicSubnet3
      SecurityGroups:
        - !ImportValue greysongundrumnetworkstack-PingSG

  greysongundrumALBLISTENER:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref greysongundrumLB
      Port: 80
      Protocol: HTTP

Parameters:
  AMI:
    Type: String
  Keyname:
    Type: String 
  PublicHomeIP:
    Type: String
  VPCCidr:
    Type: String
  PublicSubnetCidr:
    Type: String
  PublicSubnetCidr2:
    Type: String